apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-mainui
spec:
  replicas: 2
  selector:
    app: main
  template:
    metadata:
      name: httpd-pod
      labels:
        app: main
    spec:
      containers:
      - name: httpd
        image: httpd:2.2
